# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish GC SDK and get credentials

on:
  release:
    types: [created]


jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Recuperar valores de los secretos
      env:
        gcClientId: ${{ secrets.gcClientId }}
        gcClientSecret: ${{ secrets.gcClientSecret }}
      run: |
        echo "Valor de gcClientId: $gcClientId"
        echo "Valor de gcClientSecret: $gcClientSecret"


    - name: Instalar dependencias
      run: npm install purecloud-platform-client-v2

